mld2p4-2:  config/pac.m4  configure.ac  configure  mlprec/impl/level/mld_c_base_onelev_descr.f90  mlprec/impl/level/mld_d_base_onelev_descr.f90  mlprec/impl/level/mld_s_base_onelev_descr.f90  mlprec/impl/level/mld_z_base_onelev_descr.f90  mlprec/impl/mld_cmlprec_bld.f90  mlprec/impl/mld_dmlprec_bld.f90  mlprec/impl/mld_smlprec_bld.f90  mlprec/impl/mld_zmlprec_bld.f90  mlprec/mld_c_onelev_mod.f90  mlprec/mld_d_onelev_mod.f90  mlprec/mld_s_onelev_mod.f90  mlprec/mld_z_onelev_mod.f90
Fixed new informational message in onelev_descr.
Added check on PSBLAS version in configure machinery.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7284,8 +7284,8 @@ fi
 ac_objext='.o'
 ac_ext='f90'
 ac_compile='${MPIFC-$FC} -c -o conftest${ac_objext} $FMFLAG$PSBLAS_DIR/include $FMFLAG$PSBLAS_DIR/lib conftest.$ac_ext  1>&5'
-{ $as_echo "$as_me:$LINENO: checking for working source dir of PSBLAS" >&5
-$as_echo_n "checking for working source dir of PSBLAS... " >&6; }
+{ $as_echo "$as_me:$LINENO: checking for working installation of PSBLAS" >&5
+$as_echo_n "checking for working installation of PSBLAS... " >&6; }
 cat > conftest.$ac_ext <<EOF
            program test
 	       use psb_base_mod
@@ -7308,6 +7308,71 @@ $as_echo "$as_me: error: no.  Could not find working version of PSBLAS." >&2;}
    { (exit 1); exit 1; }; }
 fi
 rm -f conftest*
+
+ac_exeext=''
+ac_objext='.o'
+ac_ext='f90'
+ac_compile='${MPIFC-$FC} -c -o conftest${ac_objext} $FMFLAG$PSBLAS_DIR/include $FMFLAG$PSBLAS_DIR/lib conftest.$ac_ext  1>&5'
+ac_link='${MPIFC-$FC} -o conftest${ac_exeext} $FCFLAGS $LDFLAGS conftest.$ac_ext $FMFLAG$PSBLAS_DIR/include -L$PSBLAS_DIR/lib -lpsb_base $LIBS 1>&5'
+{ $as_echo "$as_me:$LINENO: checking for version of PSBLAS" >&5
+$as_echo_n "checking for version of PSBLAS... " >&6; }
+cat > conftest.$ac_ext <<EOF
+           program test
+	       use psb_base_mod
+               print *,psb_version_major_
+           end program test
+EOF
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && test -s conftest${ac_exeext}; then
+ pac_cv_psblas_major=`./conftest${ac_exeext} | sed 's/^ *//'`
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  pac_cv_psblas_major="unknown";
+fi
+cat > conftest.$ac_ext <<EOF
+           program test
+	       use psb_base_mod
+               print *,psb_version_minor_
+           end program test
+EOF
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && test -s conftest${ac_exeext}; then
+ pac_cv_psblas_minor=`./conftest${ac_exeext} | sed 's/^ *//'`
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  pac_cv_psblas_minor="unknown";
+fi
+rm -f conftest*
+{ $as_echo "$as_me:$LINENO: result: Done" >&5
+$as_echo "Done" >&6; }
+
+
+if test "x$pac_cv_psblas_major" == "xunknown"; then
+  { { $as_echo "$as_me:$LINENO: error: PSBLAS version major \"$pac_cv_psblas_major\"." >&5
+$as_echo "$as_me: error: PSBLAS version major \"$pac_cv_psblas_major\"." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test "x$pac_cv_psblas_minor" == "xunknown"; then
+   { { $as_echo "$as_me:$LINENO: error: PSBLAS version minor \"$pac_cv_psblas_minor\"." >&5
+$as_echo "$as_me: error: PSBLAS version minor \"$pac_cv_psblas_minor\"." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if (( $pac_cv_psblas_major < 3 )) || (( $pac_cv_psblas_minor < 1 )) ; then
+  { { $as_echo "$as_me:$LINENO: error: I need at least PSBLAS version 3.1." >&5
+$as_echo "$as_me: error: I need at least PSBLAS version 3.1." >&2;}
+   { (exit 1); exit 1; }; }
+else
+  { $as_echo "$as_me:$LINENO: Am configuring with PSBLAS version $pac_cv_psblas_major.$pac_cv_psblas_minor." >&5
+$as_echo "$as_me: Am configuring with PSBLAS version $pac_cv_psblas_major.$pac_cv_psblas_minor." >&6;}
+fi
 
 ###############################################################################
 # Variable substitutions : the Make.inc.in will have these @VARIABLES@
